project_name: shaper
before:
    hooks:
        - go mod vendor
        - go mod tidy
builds:
    -   goos:
            - linux
        goarch:
            - 386
            - amd64
        env:
            - CGO_ENABLED=0
checksum:
    name_template: 'checksums.txt'
release:
    name_template: "{{.ProjectName}}-v{{.Version}}"
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
